### ISSUE TITLE
Bonfires

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#110]
We need some bonfire maps. Issue can be closed once:

* MobArenas move you to a non-instanced Bonfire map
* The bonfire map has PC NPCs on it (for now, refiner and shop)
* Death/logout refinements are made. 
  * Players are savebound to a bonfire that corresponds with their tier until they run out of lives.
  * When a player logs out or respawns from an instance, we should (for now) have them respawn at the bonfire, and then get instantly auto-moved back into their instance.
  * Players at the bonfire without an InstId attached to them should be able to form new parties/teams
  * Catch cases like one player without an instanceID and the other with one.

**Comment by ckx** [comment]
>MobArenas move you to a non-instanced Bonfire map
41f16af879499805648b4063e47b907cda5bf574

>Death/logout refinements are made. 
41f16af879499805648b4063e47b907cda5bf574

@Pienne  when you get time we can close this if you add the current PC NPCs (shop/refine) to the bonfire map, `1@pop3`

**Comment by Pienne** [comment]
added pcnpcs and bonfire!
7f4d9fe3
