### ISSUE TITLE
Fix up instance shops

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#114]
We need to make instance-based shops that roll different items on every instance, but are functional when multiple instances are going at a time that need the shop. The default rA shops have no consideration of instances, so if you modify the base shop, it modifies it in all duplicates.

To accomplish this goal we are exploring an option of storing shop state either on the character or instance level, and regenerating it every time someone in the party/instance talks to it. 

We still may need a bit of testing though as I'm unsure of what happens if a player in instance B opens the shop when a player in instance A already had it open. Does player A's shop still function properly, or does it give stock errors when attempting to buy stuff?

**Comment by Pienne** [comment]
Just tested.

> Does player A's shop still function properly, or does it give stock errors when attempting to buy stuff?

Unfortunately, it's the latter...

![image](https://user-images.githubusercontent.com/1055372/186279758-a01a497c-d590-4b91-a78d-790a47759a06.png)

**Comment by Pienne** [comment]
for now we're going with static shops:

**Potion Trader**:
Slim reds, slim yellows, slim whites, blue potions (expensive), bottle grenades, acid bottles, green pots (DONE)

**Refiner**:
exchanges items for others.
sell 5 to 10 elu (TBD) to refiner for 1 enriched elu
1 enriched elu for ~3 elu (less than the other way)
similar exchanges for phracon + emveritarcon

**Comment by Pienne** [comment]
All done! https://www.github.com/ckx/roguenarok/commit/7716367f

For now we're using a rate of 5 regular per enriched. It's easily modifiable though.
I'll close this for now and if we decide to add more shop functionality we can add it as a separate issue or just reopen this.
