### ISSUE TITLE
Create sellable coin items

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#14]
Zeny is obtained at Kafra Shops by selling the etc item "Coins". We need DB entries for these coins, which will become monster drops. See the coin table [in the wiki](https://github.com/ckx/roguenarok/wiki/Labyrinth-Mode#currency) for more info.

This issue can be closed when we have each coin type functioning in our database.

**Comment by Pienne** [comment]
There's only one reference to coins in the wiki so far - Rusty Coins, were we going to do more?

**Comment by ckx** [comment]
Oh, I referenced the wrong article, sorry. The table is here:

https://github.com/ckx/roguenarok/wiki/Labyrinth-Mode#currency

**Comment by Pienne** [comment]
Coins are implemented and NPCable
