### ISSUE TITLE
Custom skills: Cloth/Light/Heavy Mastery

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#20]
We need empty skills setup for [Cloth/Light/Heavy armor masteries](https://github.com/ckx/roguenarok/wiki/Custom-Passives#armor-masteries) so that they appear in the skill window.

These skills don't have to do anything other than provide a description. The details are in the above wiki article.

This issue can be closed when these skills exist on both the server and clientside.

**Comment by Pienne** [comment]
skills added, descriptions will need to be revised though
