### ISSUE TITLE
Custom skills: Chemical Protection

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#21]
We need custom [Chemical Protection Armor](https://github.com/ckx/roguenarok/wiki/Custom-Passives#chemical-protect-armor) and [Full Chemical Protection](https://github.com/ckx/roguenarok/wiki/Custom-Passives#full-chemical-protection) passives.

This issue can be closed when the skills are functional on both server and client.

**Comment by Pienne** [comment]
done!
https://github.com/ckx/roguenarok/commit/96a473da34808c084fe78c1e0ec4c43c5f87d985
https://github.com/ckx/roguenarok/commit/f9088af8630ba7e59b6fe94605adeb73fe20af2a

tested on mobs that strip weapon + shield, and mobs that use demonstration. seems to work on.
