### ISSUE TITLE
Custom items for job changing

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#26]
When you reach jlvl 50 on a 1st job, you're given 2 consumable items. One transforms you into your 2-1 class, and the other into your 2-2 class. When you use one, it deletes the other.

We need these items to exist for every 2-2 class.

Then, we need an item that allows you to transcend, which is given to you when you're 2nd job jlvl 50.

All of these items should check to make sure you have 0 skill points before they're used, and they should setup your defaults according to the your [Starting Stuff](https://github.com/ckx/roguenarok/wiki/Starting-Stuff).

This is a two-parter: Pienne is in charge of generating the items in the database on the client and serverside, and I am responsible for the script functionality of the items.

This issue can be closed when you reach job 50 and are given the appropriate functional items.

**Comment by Pienne** [comment]
The items are now implemented and functional!

There are two issues atm:
1: Using the item summons an invisible NPC that persists after the item is consumed. It takes up a cell space and the cursor changes on mouseover of the NPC
2: The item is consumed before the player chooses a job, allowing for the player to lose the item without completing the process

**Comment by ckx** [comment]
Nice work. The problems you pointed out have been fixed:

1: fixed in dfb2685b.
2: fixed in ee2b361c.

The effigy items already have NoConsume on them now, but we want to add NoConsume to all our scrolls too, but that can be handled in #35.

This issue is completed for 2nd jobs now.

There are a few outstanding things to do on this issue still:

1. Add transcendent classes to the job change functions
2. Automatically give players the effigy at j50 1st job, and automatically transcend them at j50 2nd job.

These are both me, so I'm removing your assignment now.
