### ISSUE TITLE
Full reset scroll

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#28]
We need an item that completely clears all stats and skills, even SKILL_GRANT_PERM and quest skills.

Pienne's responsibility is creating the item on both server and client side.
ckx's responsibility is writing the itemscript.

This issue can be closed when the item is fully functional.

**Comment by ckx** [comment]
0a01e887 created a function called Neuralyzer which properly resets every skill a character knows, including quest skills and granted skills.

When you have time setup a separate item for this please, thanks!

**Comment by Pienne** [comment]
ez done! id 600021
