### ISSUE TITLE
Indentation errors in db/roguenarok/item_db_rogue_usable.yml

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#30]
I commented out `db/roguenarok/item_db_rogue_usable.yml` in `db\item_db.yml` because it's preventing map-server from being run. The map-server is throwing indentation errors but not saying where.

I recommend setting up [yamllint](https://github.com/adrienverge/yamllint) to help fix it. But it might still be valid YAML. In that case I recommend triple-checking all the recent work you've done on the file. Until it's resolved we won't be able to use any of our custom usable items.

This issue can be closed once `#- Path: db/roguenarok/item_db_rogue_usable.yml` is uncommented in item_db and the map-server is parsing the file properly again.

**Comment by Pienne** [comment]
found the indent, fixed
