### ISSUE TITLE
Selectable item rewards

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#4]
When we use a skill scroll box, we should be presented with a choice of 3 randomly selected skills to choose from.

We'll probably want a similar selection process for certain other rewards in the future (cards, gear, etc).

**Comment by Pienne** [comment]
Any ideas on similar mechanics in the game already? I'm struggling to think of a time where you actually select rewards.

The only things I can think of that allows you to choose an outcome are warp portal, crafting pots/weapons, and shops.

It'd be cute if using the item opens up a store with randomly generated contents, based on some random numbers unique to the player that change every time a purchase is made, and the item itself is the currency in the store... You wouldn't even need to worry about 'consumption' of the item, or even item groups maybe.

I'll have a look into how stores work. Stores with randomly generated items for sale is very on-brand, too.

**Comment by ckx** [comment]
> Any ideas on similar mechanics in the game already? I'm struggling to think of a time where you actually select rewards.

No, I can't really think of anything exactly like that, but you might want to look into Item #14527 (Dun_Tele_Scroll1), it does something similar I think.

We want to implement custom shops either way, so your store approach sounds viable to me.

**Comment by ckx** [comment]
I implemented skill scroll boxes in [8a9fad9](https://github.com/ckx/roguenarok/commit/8a9fad9bc09f82f0c4a195abf946982754d1d737). I'm not proud of it, but it works.

I'm not using item groups, and I don't think item groups are correct for this use-case because we want to do too much of our "own stuff", like store the state of a player's options if they don't make an immediate selection.

I don't know how this affects #49.
