### ISSUE TITLE
fix database load errors

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#41]
On map-server's first load our scrolls all throw an error like this:

```
* 24374 : 'R'emoveNamedSkill("SN_WINDWALK");
[Status]: Loading [1621/2487] entries from 'roguenarok/db/item_db_rogue_usable.ym[Error]:
script error on roguenarok/db/item_db_rogue_usable.yml line 24389
    parse_line: expect command, missing function name or calling undeclared function
```

Pretty sure it's because our custom scripts just aren't loaded yet, everything works well after the server is up and you @reloaditemdb. We probably need to fix a load order somewhere but I don't feel like checking right now so making an issue. 

This can be closed when the errors go away on map-server launch.

**Comment by Pienne** [comment]
pretty sure this is fixed now with a return to callfunc. local test gave no errors so closing for now
