### ISSUE TITLE
Fix skill investment

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#5]
Our skill system is broken. Despite everything being flagged as a quest skill, you can still invest skill points in anything without first consuming a skill scroll. 

I think it's because we're loading both the pre-re skill_db and the roguenarok skill_db, but I'm not really sure yet.

**Comment by Pienne** [comment]
issue was caused by load order for skilltree.yml (pre-re loaded before roguenarok)
changed load order to load roguenarok skilltree first
