### ISSUE TITLE
SkillScrollBox Items

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#50]
We need three new items which would correspond to our skill scroll boxes.

Skill Scroll boxes have three tiers, which correspond to 1st job, 2nd job, and transc skills.

Here's what the DB entries for the working testing items look like:

```
    - Id: 600001
      AegisName: testitem_1
      Name: Tao Pls Strawberry
      Type: Usable
      Flags:
        NoConsume: true
      Script: |
          callfunc "SkillScrollBoxTier1";
    - Id: 600002
      AegisName: testitem_2
      Name: Gib Tao Banana
      Type: Usable
      Flags:
        NoConsume: true
      Script: |
          callfunc "SkillScrollBoxTier2";
    - Id: 600003
      AegisName: testitem_3
      Name: PN's Test Item
      Type: Usable
      Flags:
        NoConsume: true
      Script: |
          callfunc "SkillScrollBoxTier3";
```

Can we get 3 proper items that call these functions?

Issue can be closed when new item is implemented on client and server side.

**Comment by Pienne** [comment]
all done! 
https://www.github.com/ckx/roguenarok/commit/4e884d78
