### ISSUE TITLE
Custom random option: DelayRate

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#54]
We need a "DelayRate" random option, similar to Kiel card:

`{ bonus bDelayRate,-30; },{},{}`

Can be closed when delay rate is a functioning random option.

**Comment by Pienne** [comment]
this one is done, just need to be aware of the bonus being negative when applying the option to items!

**Comment by Pienne** [comment]
just realized official item option ID 171 already exists for this so I've removed ours
