### ISSUE TITLE
Add hash tables to npc script

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#55]
We need a some kind of key value pair data structure in NPC script. We'd want the functionality to be kinda similar to arrays, here's the links for how they work to get you started on where to go for implementation: [arrays](https://github.com/ckx/roguenarok/blob/master/src/map/script.cpp#L6223) ([docs](https://github.com/ckx/roguenarok/blob/master/doc/script_commands.txt#L2203))

Appreciate it @stoopdapoop

**Comment by stoopdapoop** [comment]
looks like you have one. they're a called arrays xD

**Comment by ckx** [comment]
thank
