### ISSUE TITLE
Simple Custom Masteries

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#6]
Could you take point on implementing the custom passives? They're all outlined in this [wiki page](https://github.com/ckx/roguenarok/wiki/Custom-Passives). This issue deals with the [simple masteries](https://github.com/ckx/roguenarok/wiki/Custom-Passives#simple-masteries).

This issue can be closed when each of the Simple weapon masteries are implemented both server and clientside.

**Comment by Pienne** [comment]
made some progress today and implemented the first one: Bow Mastery

now that I have the process down the rest should be easy
the hardest part will be getting icons

**Comment by ckx** [comment]
When you have time can you rename the `ROGUE` prefix skills to `RGX`? thank.

**Comment by Pienne** [comment]
ROGUE -> RGX done
all relevant skills have been implemented, but I wish to properly test each one to ensure they are working before I close this

**Comment by Pienne** [comment]
each skill has been tested and confirmed working!
