### ISSUE TITLE
Add random options to clientside files

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#63]
We need to add our custom random options defined in `roguenarok\db\item_randomopt_db.yml` to the clientside files so that they show up.

This can be done in `enumvar.lub` and `addrandomoptionnametable.lub` in the `datainfo` directory. There are some better instructions in [this forum thread](https://rathena.org/board/topic/110692-guide-adding-custom-random-options/).

**Comment by Pienne** [comment]
all done! I gave them descriptions in this style:
"Mv.Speed + %d"
"Assumptio %d"
