### ISSUE TITLE
Get hateffect to work on units (GID)

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#90]
Mobs need a visual indicator that they are an elite. We have landed on making a state to show an aura effect, but it can be another effect if we please.

Either way, we need to implement a state that we can assign to mobs when we make them elites. For now I am assigning assumptio as a placeholder.

This can be removed once elites are no longer getting assumptio and are instead getting whatever proper state they should have.

**Comment by ckx** [comment]
actually probably better to extend hateffect to work on mob GIDs than it is to mess with states, will continue looking into it another time.

**Comment by Pienne** [comment]
all done! https://www.github.com/ckx/roguenarok/commit/79003e3d

needs to be tidied up a bit, namely:
1: currently using function overloads to handle either player or mob case when there isn't a need; should collate to one function that just takes a blocklist
2: would ideally be extended to handle other block list types too (NPC and pet come to mind)

**Comment by ckx** [comment]
Nice work
